package com.dangdang.model;

// Generated 2016-12-23 16:36:07 by Hibernate Tools 4.3.1

/**
 * ACity generated by hbm2java
 */
public class ACity implements java.io.Serializable {

    private Integer id;
    private int     code;
    private byte    type;
    private String  name;
    private Integer parentCode;
    private int     provinceId;
    private int     cityId;
    private int     districtId;

    public ACity() {
    }

    public ACity(int code, byte type, String name, int provinceId, int cityId, int districtId) {
        this.code = code;
        this.type = type;
        this.name = name;
        this.provinceId = provinceId;
        this.cityId = cityId;
        this.districtId = districtId;
    }

    public ACity(int code, byte type, String name, Integer parentCode, int provinceId, int cityId, int districtId) {
        this.code = code;
        this.type = type;
        this.name = name;
        this.parentCode = parentCode;
        this.provinceId = provinceId;
        this.cityId = cityId;
        this.districtId = districtId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getCode() {
        return this.code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public byte getType() {
        return this.type;
    }

    public void setType(byte type) {
        this.type = type;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getParentCode() {
        return this.parentCode;
    }

    public void setParentCode(Integer parentCode) {
        this.parentCode = parentCode;
    }

    public int getProvinceId() {
        return this.provinceId;
    }

    public void setProvinceId(int provinceId) {
        this.provinceId = provinceId;
    }

    public int getCityId() {
        return this.cityId;
    }

    public void setCityId(int cityId) {
        this.cityId = cityId;
    }

    public int getDistrictId() {
        return this.districtId;
    }

    public void setDistrictId(int districtId) {
        this.districtId = districtId;
    }

}
