package com.dangdang.model;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

// Generated 2016-12-23 16:36:07 by Hibernate Tools 4.3.1

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

    private long    cityId;
    private String  cityName;
    private String  zipCode;
    private Long    provinceId;
    private String  cityNameEn;
    private short   isHot;
    private Integer sortOrder;

    public City() {
    }

    public City(long cityId, short isHot) {
        this.cityId = cityId;
        this.isHot = isHot;
    }

    public City(long cityId, String cityName, String zipCode, Long provinceId, String cityNameEn, short isHot, Integer sortOrder) {
        this.cityId = cityId;
        this.cityName = cityName;
        this.zipCode = zipCode;
        this.provinceId = provinceId;
        this.cityNameEn = cityNameEn;
        this.isHot = isHot;
        this.sortOrder = sortOrder;
    }

    public long getCityId() {
        return this.cityId;
    }

    public void setCityId(long cityId) {
        this.cityId = cityId;
    }

    public String getCityName() {
        return this.cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getZipCode() {
        return this.zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public Long getProvinceId() {
        return this.provinceId;
    }

    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    public String getCityNameEn() {
        return this.cityNameEn;
    }

    public void setCityNameEn(String cityNameEn) {
        this.cityNameEn = cityNameEn;
    }

    public short getIsHot() {
        return this.isHot;
    }

    public void setIsHot(short isHot) {
        this.isHot = isHot;
    }

    public Integer getSortOrder() {
        return this.sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }

}
