package com.dangdang.model;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

// Generated 2016-12-23 16:36:07 by Hibernate Tools 4.3.1

/**
 * District generated by hbm2java
 */
public class District implements java.io.Serializable {

    private Integer districtId;
    private String  districtName;
    private int     cityId;

    public District() {
    }

    public District(int cityId) {
        this.cityId = cityId;
    }

    public District(String districtName, int cityId) {
        this.districtName = districtName;
        this.cityId = cityId;
    }

    public Integer getDistrictId() {
        return this.districtId;
    }

    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    public String getDistrictName() {
        return this.districtName;
    }

    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    public int getCityId() {
        return this.cityId;
    }

    public void setCityId(int cityId) {
        this.cityId = cityId;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }

}
