package com.dangdang.model;

// Generated 2017-5-22 15:41:07 by Hibernate Tools 4.3.1

/**
 * GwrCounty generated by hbm2java
 */
public class GwrCounty extends BaseDO {

    private Integer id;
    private String  citycode;
    private String  briefname;
    private String  countycode;
    private String  countyname;

    public GwrCounty() {
    }

    public GwrCounty(String briefname, String countycode) {
        this.briefname = briefname;
        this.countycode = countycode;
    }

    public GwrCounty(String citycode, String briefname, String countycode, String countyname) {
        this.citycode = citycode;
        this.briefname = briefname;
        this.countycode = countycode;
        this.countyname = countyname;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCitycode() {
        return this.citycode;
    }

    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }

    public String getBriefname() {
        return this.briefname;
    }

    public void setBriefname(String briefname) {
        this.briefname = briefname;
    }

    public String getCountycode() {
        return this.countycode;
    }

    public void setCountycode(String countycode) {
        this.countycode = countycode;
    }

    public String getCountyname() {
        return this.countyname;
    }

    public void setCountyname(String countyname) {
        this.countyname = countyname;
    }

}
