package com.dangdang.model;

// Generated 2017-5-22 15:41:07 by Hibernate Tools 4.3.1

/**
 * GwrCity generated by hbm2java
 */
public class GwrCity extends BaseDO {

    private Integer id;
    private String  citycode;
    private String  cityname;
    private String  cityename;
    private String  provincecode;

    public GwrCity() {
    }

    public GwrCity(String citycode) {
        this.citycode = citycode;
    }

    public GwrCity(String citycode, String cityname, String cityename, String provincecode) {
        this.citycode = citycode;
        this.cityname = cityname;
        this.cityename = cityename;
        this.provincecode = provincecode;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCitycode() {
        return this.citycode;
    }

    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }

    public String getCityname() {
        return this.cityname;
    }

    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    public String getCityename() {
        return this.cityename;
    }

    public void setCityename(String cityename) {
        this.cityename = cityename;
    }

    public String getProvincecode() {
        return this.provincecode;
    }

    public void setProvincecode(String provincecode) {
        this.provincecode = provincecode;
    }

}
