package com.dangdang.model;

// Generated 2016-12-23 16:36:07 by Hibernate Tools 4.3.1

/**
 * PassportDeliveryAddress generated by hbm2java
 */
public class PassportDeliveryAddress implements java.io.Serializable {

    private String  id;
    private String  passportUserId;
    private Long    provinceId;
    private Long    cityId;
    private Long    districtId;
    private String  postCode;
    private String  receiveDeliveryPerson;
    private String  receiveDeliveryMobile;
    private Boolean isDefault;
    private Boolean isVisible;
    private String  deliveryAddress;
    private int     createTime;

    public PassportDeliveryAddress() {
    }

    public PassportDeliveryAddress(String id, int createTime) {
        this.id = id;
        this.createTime = createTime;
    }

    public PassportDeliveryAddress(String id, String passportUserId, Long provinceId, Long cityId, Long districtId, String postCode,
            String receiveDeliveryPerson, String receiveDeliveryMobile, Boolean isDefault, Boolean isVisible, String deliveryAddress, int createTime) {
        this.id = id;
        this.passportUserId = passportUserId;
        this.provinceId = provinceId;
        this.cityId = cityId;
        this.districtId = districtId;
        this.postCode = postCode;
        this.receiveDeliveryPerson = receiveDeliveryPerson;
        this.receiveDeliveryMobile = receiveDeliveryMobile;
        this.isDefault = isDefault;
        this.isVisible = isVisible;
        this.deliveryAddress = deliveryAddress;
        this.createTime = createTime;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPassportUserId() {
        return this.passportUserId;
    }

    public void setPassportUserId(String passportUserId) {
        this.passportUserId = passportUserId;
    }

    public Long getProvinceId() {
        return this.provinceId;
    }

    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    public Long getCityId() {
        return this.cityId;
    }

    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    public Long getDistrictId() {
        return this.districtId;
    }

    public void setDistrictId(Long districtId) {
        this.districtId = districtId;
    }

    public String getPostCode() {
        return this.postCode;
    }

    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    public String getReceiveDeliveryPerson() {
        return this.receiveDeliveryPerson;
    }

    public void setReceiveDeliveryPerson(String receiveDeliveryPerson) {
        this.receiveDeliveryPerson = receiveDeliveryPerson;
    }

    public String getReceiveDeliveryMobile() {
        return this.receiveDeliveryMobile;
    }

    public void setReceiveDeliveryMobile(String receiveDeliveryMobile) {
        this.receiveDeliveryMobile = receiveDeliveryMobile;
    }

    public Boolean getIsDefault() {
        return this.isDefault;
    }

    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    public Boolean getIsVisible() {
        return this.isVisible;
    }

    public void setIsVisible(Boolean isVisible) {
        this.isVisible = isVisible;
    }

    public String getDeliveryAddress() {
        return this.deliveryAddress;
    }

    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

    public int getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(int createTime) {
        this.createTime = createTime;
    }

}
