package com.dangdang.model;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

// Generated 2016-12-23 16:36:07 by Hibernate Tools 4.3.1

/**
 * Province generated by hbm2java
 */
public class Province implements java.io.Serializable {

    private long   provinceId;
    private String provinceName;

    public Province() {
    }

    public Province(long provinceId) {
        this.provinceId = provinceId;
    }

    public Province(long provinceId, String provinceName) {
        this.provinceId = provinceId;
        this.provinceName = provinceName;
    }

    public long getProvinceId() {
        return this.provinceId;
    }

    public void setProvinceId(long provinceId) {
        this.provinceId = provinceId;
    }

    public String getProvinceName() {
        return this.provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }

}
